# -*- coding: utf-8 -*-
#
# Custom background and gear icon Add-on for Anki
# Copyright (C)  2022 
#
# This file was automatically generated by Anki Add-on Builder v1.0.0-dev.2
# It is subject to the same licensing terms as the rest of the program
# (see the LICENSE file which accompanies this program).
#
# WARNING! All changes made in this file will be lost!

"""
Initializes generated Qt forms/resources
"""

__all__ = [
    "settings_dialog"
]

from . import settings_dialog
